### ISSUE TITLE
Container doesn't recognize mocked services

### ISSUE THREAD

**Issue by karolsojko** [PolishSymfonyCommunity/SymfonyMockerContainer#2]
I cannot get this running for some time now so here's the story:
## Project creation

``` bash
composer create-project symfony/framework-standard-edition test-symfony-project/ 2.2.1
```

Then I've edited composer json to have:

``` json
    "require-dev": {
        "behat/behat": "2.4.*@stable",
        "behat/symfony2-extension":     "dev-master",
        "behat/mink-extension":         "dev-master",
        "behat/mink-browserkit-driver": "dev-master",
        "behat/common-contexts":        "dev-master",
        "polishsymfonycommunity/symfony-mocker-container": "*",
        "kriswallsmith/buzz": "dev-master"
    }
```
## Behat

So this is the scenario:

``` yml
Feature:
    some feature

    Scenario: Some scenario
        Given some service is ready
        When I send a GET request to "/demo/hello/test"
        And the response code should be 200
```

And this is the context class:

``` php
<?php

namespace Acme\DemoBundle\Features\Context;

use Behat\Behat\Context\BehatContext;
use Behat\Symfony2Extension\Context\KernelAwareInterface;
use Behat\CommonContexts\WebApiContext;

use Symfony\Component\HttpKernel\KernelInterface;

class FeatureContext extends BehatContext implements KernelAwareInterface
{
    /**
     * @var KernelInterface
     */
    protected $kernel;

    /**
     * @AfterScenario
     */
    public function tearDown()
    {
        // verify pending expectations
        \Mockery::close();
    }

    /**
     * @Given /^some service is ready$/
     */
    public function someServiceIsReady()
    {
        $this->getContainer()->mock('some_service', 'Acme\DemoBundle\Something\SomeService')
            ->shouldReceive('hello')
            ->once()
            ->andReturn(true);
        var_dump(array_keys($this->getContainer()->getMockedServices()));
    }

    /**
     * Initializes context.
     * Every scenario gets it's own context object.
     *
     * @param array $parameters context parameters (set them up through behat.yml)
     */
    public function __construct(array $parameters)
    {
        $this->useContext('webapi', new WebApiContext($parameters['base_url']));

        $this->getSubcontext('webapi')
            ->setPlaceHolder('BASE_URL', rtrim($parameters['base_url'], '/'));
    }

    /**
     * @param \Symfony\Component\HttpKernel\KernelInterface $kernel
     */
    public function setKernel(KernelInterface $kernel)
    {
        $this->kernel = $kernel;
    }

    /**
     * @return \Symfony\Component\DependencyInjection\ContainerInterface
     */
    public function getContainer()
    {
        return $this->kernel->getContainer();
    }
}
```

And the behat.yml file:

``` yml
default:
  context:
    class:  Acme\DemoBundle\Features\Context\FeatureContext
    parameters:
      base_url: 'http://test.dev/app_test.php'
  formatter:
    name: junit, progress
    parameters:
      output_path: app/logs/behat,
      language: en
  extensions:
    Behat\Symfony2Extension\Extension:
      mink_driver: true
      kernel:
        env: test
        debug: true
    Behat\MinkExtension\Extension:
      base_url: 'http://test.dev/app_test.php'
      default_session: symfony2
```
## Implementation

In services.xml:

``` xml
<service id="some_service" class="Acme\DemoBundle\Something\SomeService"></service>
```

Then I've got this service class:

``` php
<?php

namespace Acme\DemoBundle\Something;

class SomeService
{
    public function hello()
    {
        return 'hello';
    }
}

```

And in controller:

``` php
    /**
     * @Route("/hello/{name}", name="_demo_hello")
     * @Template()
     */
    public function helloAction($name)
    {
        var_dump(array_keys($this->container->getMockedServices()));
        $someService = $this->get('some_service');
        $hello = $someService->hello();

        return array('name' => $hello);
    }
```

As you can see I've put some `var_dump`s to see if the services are mocked. In the context the `var_dump` gives:

``` php
array(1) {
  [0] =>
  string(12) "some_service"
}
```

and the second one (in controller) gives an empty array.

Running the scenarios gives me:

``` bash
  [Mockery\Exception\InvalidCountException]                                                                                  
  Exception has been thrown in "afterScenario" hook, defined in Acme\DemoBundle\Features\Context\FeatureContext::tearDown()  

  Method hello() from Acme\DemoBundle\Something\SomeService should be called                                                 
   exactly 1 times but called 0 times.
```

Can't seem to get this container to mock services.
